### ISSUE TITLE
Start date based on due date broken when due date has time specified

### ISSUE THREAD

**Issue by RoccoMathijn** [Hoffelhas/automation-todoist#24]
I have a recurring task due every Tuesday at 22:00. I defined start date as ‘start=due-0d’. It’s still labeled as next action, it shouldn’t because today is Sunday.

When 22:00 is removed from the task the task is correctly not labeled

**Comment by Hoffelhas** [comment]
Hi there, thanks for reaching out with this bug, and sorry it took me so long to get back to you. Since I'm currently working on a big overhaul of Autodoist, the pull request can't really be used any more, but I've included a fix for this based on your work in the latest dev version such that it is ready for the next release.

For now I'm closing this one, feel free to reopen if a similar issue still happens in the future.
