### ISSUE TITLE
Not detecting new tasks / unable to detect my next_action label

### ISSUE THREAD

**Issue by jleseane23** [Hoffelhas/automation-todoist#28]
I setup Autodoist in a docker container using the [following instructions](https://github.com/Hoffelhas/autodoist/issues/9). It's been working up until now. Before this happened, the container had an uptime of 4 days.

Today, I noticed that any new tasks I input in Todoist weren't receiving my next_action label. I tried to stop the container and edit the command so it'll have a sync time of 45 seconds instead of 5. When I tried to start the container back up, I'm getting errors and it's not acting as if my next_action label isn't there. Here are the following errors.

I'm going to try to run Autodoist directly from my PC to see if I get the same errors

[_autodoist_logs.txt](https://github.com/Hoffelhas/autodoist/files/9698870/_autodoist_logs.txt)

`  File "/app/autodoist.py", line 166, in initialise
    label_id = verify_label_existance(args, api, args.label, 1)
  File "/app/autodoist.py", line 91, in verify_label_existance
    response = query_yes_no(
  File "/app/autodoist.py", line 65, in query_yes_no
    choice = input().lower()
EOFError: EOF when reading a line
Do you want to automatically create this label? [Y/n] Q2022-10-03 15:31:05 INFO     You are running with the following functionalities:

   Next action labelling mode: Enabled
   Regenerate sub-tasks mode: Enabled
   Shifted end-of-day mode: Disabled

2022-10-03 15:31:05 INFO     

Label 'next_action' doesn't exist in your Todoist

Traceback (most recent call last):
  File "/app/autodoist.py", line 1005, in <module>
    main()
  File "/app/autodoist.py", line 959, in main
    api, label_id, regen_labels_id = initialise(args)
  File "/app/autodoist.py", line 166, in initialise
    label_id = verify_label_existance(args, api, args.label, 1)
  File "/app/autodoist.py", line 91, in verify_label_existance
    response = query_yes_no(
  File "/app/autodoist.py", line 65, in query_yes_no
    choice = input().lower()
EOFError: EOF when reading a line
Do you want to automatically create this label? [Y/n] Q2022-10-03 15:31:07 INFO     You are running with the following functionalities:

   Next action labelling mode: Enabled
   Regenerate sub-tasks mode: Enabled
   Shifted end-of-day mode: Disabled

2022-10-03 15:31:07 INFO     

Label 'next_action' doesn't exist in your Todoist

Traceback (most recent call last):
  File "/app/autodoist.py", line 1005, in <module>
    main()
  File "/app/autodoist.py", line 959, in main
    api, label_id, regen_labels_id = initialise(args)
  File "/app/autodoist.py", line 166, in initialise
    label_id = verify_label_existance(args, api, args.label, 1)
  File "/app/autodoist.py", line 91, in verify_label_existance
    response = query_yes_no(
  File "/app/autodoist.py", line 65, in query_yes_no
    choice = input().lower()
EOFError: EOF when reading a line
Do you want to automatically create this label? [Y/n] Q2022-10-03 15:31:10 INFO     You are running with the following functionalities:

   Next action labelling mode: Enabled
   Regenerate sub-tasks mode: Enabled
   Shifted end-of-day mode: Disabled

2022-10-03 15:31:10 INFO     

Label 'next_action' doesn't exist in your Todoist

Traceback (most recent call last):
  File "/app/autodoist.py", line 1005, in <module>
    main()
  File "/app/autodoist.py", line 959, in main
    api, label_id, regen_labels_id = initialise(args)
  File "/app/autodoist.py", line 166, in initialise
    label_id = verify_label_existance(args, api, args.label, 1)
  File "/app/autodoist.py", line 91, in verify_label_existance
    response = query_yes_no(
  File "/app/autodoist.py", line 65, in query_yes_no
    choice = input().lower()
EOFError: EOF when reading a line
Do you want to automatically create this label? [Y/n] Q2022-10-03 15:31:15 INFO     You are running with the following functionalities:

   Next action labelling mode: Enabled
   Regenerate sub-tasks mode: Enabled
   Shifted end-of-day mode: Disabled

2022-10-03 15:31:15 INFO     

Label 'next_action' doesn't exist in your Todoist

Traceback (most recent call last):
  File "/app/autodoist.py", line 1005, in <module>
    main()
  File "/app/autodoist.py", line 959, in main
    api, label_id, regen_labels_id = initialise(args)
  File "/app/autodoist.py", line 166, in initialise
    label_id = verify_label_existance(args, api, args.label, 1)
  File "/app/autodoist.py", line 91, in verify_label_existance
    response = query_yes_no(
  File "/app/autodoist.py", line 65, in query_yes_no
    choice = input().lower()
EOFError: EOF when reading a line
Do you want to automatically create this label? [Y/n] 
`

**Comment by machielkreiken** [comment]
Same issue here. No longer detecting my changes. I recreated the API token hoping it would fix things, but didn't.

It's starting fine, but detects nothing:
![CleanShot 2022-12-09 at 13 22 23](https://user-images.githubusercontent.com/28918979/206701634-45bb1d82-c1bb-49ed-bb3f-b416ec2d14e7.png)

**Comment by ShayHill** [comment]
Same here. Was working for months previously. Updated to latest python todoist API. No help. Ran locally. No help. This is a bug or API change in Todoist. I would like to investigate, but haven't time ATM.

**Comment by ShayHill** [comment]
Losing this automation was a big impediment to my workflow. I have created a similar project with the updated API:
[todoist_bot](https://github.com/ShayHill/todoist_bot)

**Comment by Hoffelhas** [comment]
Hi there! Thanks all for reaching out and looking into this. Sorry I haven’t been able to reply yet, life is bit hectic at the moment. I'll try to find some time this weekend to take a proper look at this too, since it’s a pretty impactful bug indeed.

**Comment by ShayHill** [comment]
Love your project. Has been the reason I’ve stuck with Todoist. Thank you for everything!

**Comment by Hoffelhas** [comment]
Well, fun times! Todoist went from v1.x.x to v2 of their API. The old one is still 'working', but apparently only syncs to an older version all your projects/tasks from a few months ago.

The API has changed quite significantly, so I'm currently working through the entire code to make it compatible again.

**Comment by Hoffelhas** [comment]
Oof bad news. The new API's of Todoist doesn't allow creating custom properties for tasks any more. This was a functionality that I used to assign my own meta-data, which Autodoist could use to keep track of stuff and work properly. 

Even if rewrite all the syntax to the new API, a lot of core functionalities simply don't work any more. I will need to give this some additional thought to see if I can find some kind of workaround or else use an alternative approach to get the same things done. Unfortunately, no quick fix for now.

I'll keep you posted.

**Comment by JoergBr** [comment]
Oh sh... but thank you for looking into it and I'll keep fingers crossed!

________________________________
Von: Hoffelhas ***@***.***>
Gesendet: Sonntag, 18. Dezember 2022 14:00
An: Hoffelhas/autodoist
Cc: Subscribed
Betreff: Re: [Hoffelhas/autodoist] Not detecting new tasks / unable to detect my next_action label (Issue #28)


Oof bad news. The new API's of Todoist don't allow creating custom properties for tasks any more. This was a functionality that I used to assign my own meta-data, which Autodoist could use to keep track of stuff and work properly.

Even if rewrite all the syntax to the new API, a lot of core functionalities simply don't work any more. I will need to give this some additional though to see if I can find some kind of workaround or else use an alternative approach to get the same things done. Unfortunately, no quick fix for now.

I'll keep you posted.

**Comment by Hoffelhas** [comment]
Hi all, I was able to find a workaround and have just pushed a working version to the dev branch. Currently only labelling is working, I've disabled most of the other features for now so I could focus on the problem at hand.

Before releasing a new master version, there are a few minor things I still want to do:
- First of all I'll slightly tweak how types are specified on each level (project, section, top-task, sub-tasks), in order to have a better handling on how sections and sub-tasks behave. This is because the code was developed before sections where even a thing, and the amount of subtasks possible where fewer. Should give you guys a bit more flexibility.
- And of course, see if I can easily reactivate the other functionalities.

In any case, v2.0 planned to be released relatively soon.

**Comment by RoccoMathijn** [comment]
@Hoffelhas I have holidays and some time left this week. LMK if you want to pair up or divide some work. Let's get this thing working again.

**Comment by Hoffelhas** [comment]
@RoccoMathijn Hi there, thanks a lot for your help! First bullet point is now done, it's mostly fixing the other functionalities. I actually do have one I'm stuck with currently and will likely only be able to continue with this weekend.

I've put a new branch up, '26_due_date', where I'm trying to get the 'Postpone the end-of-day' functionality working again. The final thing that needs to happen is that the updated due date needs to be send back to Todoist, which currently is done on line 769 with the REST API. However, this will remove the 'due string' / recurring settings from the task, or basically, updating the due date with the REST API breaks the task. Brilliant.

The alternative would be to use the sync API. An example can be seen if you manually run the 'get_all_data' function (this uses 'get' that's imported from todoist_api_python.http_requests); it actually spits back data. Now this is good, since the Sync API mentions that [you can update the due date too](https://developer.todoist.com/sync/v9/#update-the-content-and-due-date-of-a-task). It also mentions that 'Sync API requests should be made in HTTP POST', so perhaps it's possible to use the imported 'post' function. Unfortunately I have not been able to work it out yet.

If you would have some time to poke around this issue a bit, that would be much appreciated!

**Comment by RoccoMathijn** [comment]
The sync api has the same behaviour.

But although it's stated in the api docs that: `Please note that only one of the due_* fields can be used at the same time (due_lang is a special case).` I found out that we can both provide the due_date and due_string.

So with `api.update_task(task_id=task.id, due_date=today_str, due_string=task.due.string)` it seems to work.

**Comment by Hoffelhas** [comment]
Oh wow, great find. That certainly makes things a lot easier; I'll implement that. Thanks a lot!

**Comment by Hoffelhas** [comment]
Good news everyone!

I've been able to work through all the important parts. I'll spend some time updating the README, do some final testing, and the goal is to release v2.0.0 this weekend!

Only resetting recurring tasks has not been enabled yet, since nowadays it's a [core functionality of Todoist itself](https://todoist.com/help/articles/can-i-reset-sub-tasks). However:
- it's still more limited than Autodoist
- it does not restore the original order of the sub-tasks 
- deeper sub-tasks can't be reset

Unfortunately the REST API doesn't show completed tasks, which makes resetting them a bit complicated. I've placed a ticket with the Todoist devs to figure this one out, so for now this feature might be made available again in a future release.

**Comment by Hoffelhas** [comment]
I might have gone a bit overboard with it:

![image](https://user-images.githubusercontent.com/19412013/212568557-79c5910b-8ade-4386-a1e1-51f85dac4161.png)

But v2.0 is now released!

Thanks to all of you for your support and feedback! It was a great help to make this possible. If any new bugs arise, please feel free to open a new issue tracker. For now, I'll close this one and I'm going to get some sleep.
