### ISSUE TITLE
postpone all overdue tasks?

### ISSUE THREAD

**Issue by benjiwheeler** [Hoffelhas/automation-todoist#29]
one feature I'd find useful would be the ability to postpone all overdue tasks with a click or two. Maybe I could specify a timeframe -- e.g., from 3 days in the future to 20 days in the future -- and the overdue items could be randomly assigned to days in that range? A bonus would be if recurring tasks would not be postponed past their next occurring date.

**Comment by Hoffelhas** [comment]
Hi there, thanks for reaching out!

My initial thought is that this would not suit Autodoist. I am a bit biased, since I'm following the GTD approach, but it's good practice to 1) create tasks that you can actually achieve, 2) plan them when you can actually do them, and 3) have weekly reviews to tidy up whatever tool you are using to manage your tasks. From the looks of it, creating a feature to clean up (too) many overdue tasks and putting them at a random dates would violates all three of these aspects. Changing your workflow and habits could prove to be a much greater help in the long run, than a feature that solves the effects.

Out of interest and to get a better understanding of this, could you give me a bit more information regarding your current workflow and what creates this situation?

**Comment by benjiwheeler** [comment]
I hear you, @Hoffelhas! My whole workflow has a lot of parts, but one thing it involves is many repeating tasks that don't _have_ to happen on any given day, but do _have_ to happen eventually -- doing laundry, reducing my email backlog, etc. It's great to have those recur, because I might not think to do them otherwise. But if they don't all get done, then they start to collect as overdue items. When a bunch of those become overdue, I often just go down the list and set each one to "postpone" until the next scheduled day. I really want to just be able to click once to postpone all of them. I think that's part of a healthy overall workflow!
