### ISSUE TITLE
Use comments instead of suffix in title

### ISSUE THREAD

**Issue by jrabensc** [Hoffelhas/automation-todoist#3]
It would be nice to use comments of tasks, projects or sections for the suffix instead of using the title. This would be a more clean approach.

Example: When I put "sequential" in the first comment of a task, all subtasks are treated the same as when I put "--" in the title.

**Comment by Hoffelhas** [comment]
Hi there, thanks for the suggestion. I like the idea of the cleaner approach, so I've taken a quick look at it. 

As far as I can see sections don't have a dedicated way to save comments like projects and tasks do, so that would mean that even though projects and tasks look clean, sections won't, which makes it quite inconsistent. I also see that people use the first task in a section as 'note' as a sort of workaround, but this is just applying duct tape for the sake of making things work. If there would be a more consistent way of doing this, I'd be more fond of it.

In addition, I can't seem to find a way to access a comment content directly from the project or item data. That's not a big issue, since it's possible to find and match the corresponding project/item id with all the available notes. However, this is a whole layer of additional load, which will make the program slower; I'd have to look how significant this impact will be.

So for now, don't expect this in the next release, but I'll keep it in mind to find a way in which it could work nicely.
